/**
 * Semantic colors for light / dark. Consumed by Unistyles themes only — use `theme.colors.*` in components.
 */
export type AppColors = {
  background: string;
  backgroundSecondary: string;
  backgroundTertiary: string;
  border: string;
  borderMuted: string;
  borderStrong: string;
  text: string;
  textSecondary: string;
  textMuted: string;
  textDisabled: string;
  textInk: string;
  link: string;
  tint: string;
  primary: string;
  onPrimary: string;
  error: string;
  success: string;
  overlay: string;
  shadow: string;
  shadowStrong: string;
  oursAccent: string;
  oursAccentStrong: string;
  oursBgSoft: string;
  oursBorderSoft: string;
  oursBgTint: string;
  oursStatBar: string;
  rivalAccent: string;
  rivalAccentStrong: string;
  rivalBgSoft: string;
  rivalBorderSoft: string;
  rivalBgTint: string;
  rivalStatBar: string;
  tabPillOurs: string;
  tabPillRival: string;
  tabLabelMuted: string;
  inputBorder: string;
  modalHeaderDividerOurs: string;
  modalHeaderDividerRival: string;
  statTrack: string;
  compareVsMark: string;
  warningBg: string;
  warningText: string;
  chipSpritePlaceholder: string;
  neutralSurface: string;
  bannerInfoText: string;
  secondaryControlBg: string;
  ionIconMuted: string;
  pokeapiLink: string;
  /** Info tab / marketing surfaces */
  pageMuted: string;
  creamCard: string;
  infoCardBorder: string;
};

export const lightColors: AppColors = {
  background: '#ffffff',
  backgroundSecondary: '#fafafa',
  backgroundTertiary: '#f4f4f5',
  border: '#e4e4e7',
  borderMuted: '#f4f4f5',
  borderStrong: '#d4d4d8',
  text: '#18181b',
  textSecondary: '#52525b',
  textMuted: '#71717a',
  textDisabled: '#a1a1aa',
  textInk: '#27272a',
  link: '#2563eb',
  tint: '#2f95dc',
  primary: '#2563eb',
  onPrimary: '#ffffff',
  error: '#b91c1c',
  success: '#15803d',
  overlay: 'rgba(0,0,0,0.45)',
  shadow: '#000000',
  shadowStrong: '#27272a',
  oursAccent: '#1d4ed8',
  oursAccentStrong: '#2563eb',
  oursBgSoft: '#eff6ff',
  oursBorderSoft: '#93c5fd',
  oursBgTint: '#dbeafe',
  oursStatBar: '#6366f1',
  rivalAccent: '#b91c1c',
  rivalAccentStrong: '#dc2626',
  rivalBgSoft: '#fef2f2',
  rivalBorderSoft: '#fecaca',
  rivalBgTint: '#fee2e2',
  rivalStatBar: '#dc2626',
  tabPillOurs: '#dbeafe',
  tabPillRival: '#fee2e2',
  tabLabelMuted: '#71717a',
  inputBorder: '#d4d4d8',
  modalHeaderDividerOurs: '#bfdbfe',
  modalHeaderDividerRival: '#fecaca',
  statTrack: '#e4e4e7',
  compareVsMark: '#a1a1aa',
  warningBg: '#fef3c7',
  warningText: '#92400e',
  chipSpritePlaceholder: '#f4f4f5',
  neutralSurface: '#f4f4f5',
  bannerInfoText: '#1e40af',
  secondaryControlBg: '#e4e4e7',
  ionIconMuted: '#71717a',
  pokeapiLink: '#2e78b7',
  pageMuted: '#f4f4f5',
  creamCard: '#fffbf7',
  infoCardBorder: '#fecaca',
};

export const darkColors: AppColors = {
  background: '#09090b',
  backgroundSecondary: '#18181b',
  backgroundTertiary: '#27272a',
  border: '#3f3f46',
  borderMuted: '#27272a',
  borderStrong: '#52525b',
  text: '#fafafa',
  textSecondary: '#a1a1aa',
  textMuted: '#a1a1aa',
  textDisabled: '#71717a',
  textInk: '#e4e4e7',
  link: '#60a5fa',
  tint: '#ffffff',
  primary: '#3b82f6',
  onPrimary: '#ffffff',
  error: '#f87171',
  success: '#4ade80',
  overlay: 'rgba(0,0,0,0.65)',
  shadow: '#000000',
  shadowStrong: '#18181b',
  oursAccent: '#93c5fd',
  oursAccentStrong: '#60a5fa',
  oursBgSoft: '#172554',
  oursBorderSoft: '#3b82f6',
  oursBgTint: '#1e3a5f',
  oursStatBar: '#818cf8',
  rivalAccent: '#fca5a5',
  rivalAccentStrong: '#f87171',
  rivalBgSoft: '#450a0a',
  rivalBorderSoft: '#991b1b',
  rivalBgTint: '#450a0a',
  rivalStatBar: '#f87171',
  tabPillOurs: '#172554',
  tabPillRival: '#450a0a',
  tabLabelMuted: '#a1a1aa',
  inputBorder: '#52525b',
  modalHeaderDividerOurs: '#1e3a8a',
  modalHeaderDividerRival: '#7f1d1d',
  statTrack: '#3f3f46',
  compareVsMark: '#71717a',
  warningBg: '#422006',
  warningText: '#fcd34d',
  chipSpritePlaceholder: '#27272a',
  neutralSurface: '#27272a',
  bannerInfoText: '#93c5fd',
  secondaryControlBg: '#3f3f46',
  ionIconMuted: '#a1a1aa',
  pokeapiLink: '#7dd3fc',
  pageMuted: '#0f0f14',
  creamCard: '#1e1e2e',
  infoCardBorder: '#7f1d1d',
};
